[build]
builder = "nixpacks"
nixpacksConfigPath = "backend/nixpacks.json"
watchPatterns = ["backend/**"]

[deploy]
startCommand = "cd backend && npx prisma migrate deploy && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
