[build]
builder = "nixpacks"
nixpacksConfigPath = "backend/nixpacks.json"

[deploy]
workingDirectory = "backend"
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
